version: '3.4'

services:
  api1:
    image: ${DOCKER_REGISTRY-}api1
    build:
      context: .
      dockerfile: Api1/Dockerfile
    container_name: api1

  api2:
    image: ${DOCKER_REGISTRY-}api2
    build:
      context: .
      dockerfile: Api2/Dockerfile
    container_name: api2

  api3:
    image: ${DOCKER_REGISTRY-}api3
    build:
      context: .
      dockerfile: Api3/Dockerfile
    container_name: api3

  healthui:
    image: ${DOCKER_REGISTRY-}healthui
    build:
      context: .
      dockerfile: HealthUI/Dockerfile
    container_name: healthui
    depends_on:
      - sqlserver
 
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password12!
    ports:
      - 1433:1433
    volumes:
      - healthsqlstorage:/var/opt/mssql


volumes:
  healthsqlstorage:

